# Generated by Django 4.2.2 on 2023-07-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadesBNCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(max_length=255, verbose_name='Habilidade da BNCC')),
            ],
        ),
        migrations.RemoveField(
            model_name='questao',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='habilidades_abncc',
        ),
        migrations.AlterField(
            model_name='questao',
            name='suporte_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='suporte_imagem', verbose_name='Suporte de Imagem'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='suporte_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Suporte de Texto'),
        ),
        migrations.AddField(
            model_name='questao',
            name='habilidades_abncc',
            field=models.ManyToManyField(to='simulados.habilidadesbncc', verbose_name='Habilidades da BNCC'),
        ),
    ]
