# Generated by Django 4.2.2 on 2023-07-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0002_habilidadesbncc_remove_questao_ano_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_a',
            field=models.TextField(max_length=255, verbose_name='Alternativa A'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_b',
            field=models.TextField(verbose_name='Alternativa B'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_c',
            field=models.TextField(verbose_name='Alternativa C'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_d',
            field=models.TextField(verbose_name='Alternativa D'),
        ),
    ]
