# Generated by Django 4.2.2 on 2023-07-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_professor_email'),
        ('simulados', '0003_alter_questao_options_alter_questao_alternativa_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.professor', verbose_name='Professor'),
            preserve_default=False,
        ),
    ]
