# Generated by Django 4.2.2 on 2023-07-04 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_professor_email'),
        ('simulados', '0004_simulado_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descritor', models.CharField(max_length=255, verbose_name='Descritor')),
            ],
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='quantidade_respostas_a',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='quantidade_respostas_b',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='quantidade_respostas_c',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='quantidade_respostas_corretas',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='quantidade_respostas_d',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='simulado',
        ),
        migrations.RemoveField(
            model_name='simulado',
            name='questoes_referencia',
        ),
        migrations.AddField(
            model_name='questaoreferencia',
            name='quantidade_respostas_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de respostas A'),
        ),
        migrations.AddField(
            model_name='questaoreferencia',
            name='quantidade_respostas_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de respostas B'),
        ),
        migrations.AddField(
            model_name='questaoreferencia',
            name='quantidade_respostas_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de respostas C'),
        ),
        migrations.AddField(
            model_name='questaoreferencia',
            name='quantidade_respostas_corretas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de respostas corretas'),
        ),
        migrations.AddField(
            model_name='questaoreferencia',
            name='quantidade_respostas_d',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de respostas D'),
        ),
        migrations.AddField(
            model_name='questaoreferencia',
            name='simulado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simulados.simulado', verbose_name='Simulado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='acertou',
            field=models.BooleanField(default=False, verbose_name='Acertou?'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno', verbose_name='Aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='questao_referencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simulados.questaoreferencia', verbose_name='Questão de referência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default=1, max_length=255, verbose_name='Resposta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_a',
            field=models.TextField(verbose_name='Alternativa A'),
        ),
    ]
