# Generated by Django 4.2.2 on 2023-07-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0005_descritor_remove_resposta_quantidade_respostas_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descritor',
            options={'verbose_name': 'Descritor', 'verbose_name_plural': 'Descritores'},
        ),
        migrations.RemoveField(
            model_name='questao',
            name='descritor',
        ),
        migrations.AddField(
            model_name='questao',
            name='descritor',
            field=models.ManyToManyField(to='simulados.descritor', verbose_name='Descritor'),
        ),
    ]
