# Generated by Django 4.2.2 on 2023-07-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0007_nivelproficiencia_remove_questao_nivel_proficiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='alternativa_a_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='alternativa_a_imagem', verbose_name='Alternativa A Imagem'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_b_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='alternativa_b_imagem', verbose_name='Alternativa B Imagem'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_c_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='alternativa_c_imagem', verbose_name='Alternativa C Imagem'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_d_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='alternativa_d_imagem', verbose_name='Alternativa D Imagem'),
        ),
    ]
