# Generated by Django 4.2.2 on 2023-07-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0008_questao_alternativa_a_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='alternativa_a',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativa A'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_b',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativa B'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_c',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativa C'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_d',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativa D'),
        ),
    ]
