# Generated by Django 4.2.2 on 2023-07-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0011_alter_questao_habilidades_abncc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='visivel',
            field=models.BooleanField(default=True, verbose_name='Pergunta Visível Para Todos?'),
        ),
    ]
