# Generated by Django 4.2.2 on 2023-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0012_questao_visivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidadesbncc',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
    ]
