# Generated by Django 4.2.2 on 2023-07-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0013_habilidadesbncc_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidadesbncc',
            name='ano',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ano'),
        ),
    ]
