# Generated by Django 4.2.2 on 2023-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0014_alter_habilidadesbncc_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='habilidades_abncc_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades da BNCC (Texto)'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=models.TextField(blank=True, null=True, verbose_name='Enunciado'),
        ),
    ]
