# Generated by Django 4.2.2 on 2023-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0015_questao_habilidades_abncc_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='simulado_cadastrado',
            field=models.BooleanField(default=False, verbose_name='Simulado cadastrado?'),
        ),
    ]
