# Generated by Django 4.2.2 on 2023-07-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_professor_options'),
        ('simulados', '0016_simulado_simulado_cadastrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestaoProficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao_facil', models.IntegerField(verbose_name='Número da questão fácil')),
                ('questao_facil', models.TextField(verbose_name='Questão fácil')),
                ('numero_questao_medio', models.IntegerField(verbose_name='Número da questão médio')),
                ('questao_medio', models.TextField(verbose_name='Questão médio')),
                ('numero_questao_dificil', models.IntegerField(verbose_name='Número da questão difícil')),
                ('questao_dificil', models.TextField(verbose_name='Questão difícil')),
            ],
        ),
        migrations.RemoveField(
            model_name='simulado',
            name='simulado_cadastrado',
        ),
        migrations.AddField(
            model_name='simulado',
            name='tipo_simulado',
            field=models.CharField(blank=True, choices=[('questoes_construidas', 'Questões Construídas'), ('questoes_cadastradas', 'Questões Cadastradas'), ('questoes_proficiencia', 'Questões de Proficiência')], max_length=255, null=True, verbose_name='Tipo do simulado'),
        ),
        migrations.CreateModel(
            name='RespostaProficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao_facil_acertou', models.BooleanField(default=False, verbose_name='Acertou a questão fácil?')),
                ('questao_medio_acertou', models.BooleanField(default=False, verbose_name='Acertou a questão médio?')),
                ('questao_dificil_acertou', models.BooleanField(default=False, verbose_name='Acertou a questão difícil?')),
                ('pontuacao', models.FloatField(blank=True, null=True, verbose_name='Pontuação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno', verbose_name='Aluno')),
                ('questao_proficiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulados.questaoproficiencia', verbose_name='Questão de Proficiência')),
            ],
        ),
        migrations.AddField(
            model_name='questaoproficiencia',
            name='simulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulados.simulado', verbose_name='Simulado'),
        ),
    ]
