# Generated by Django 4.2.2 on 2023-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0017_questaoproficiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaoproficiencia',
            name='habilidade_bncc',
            field=models.CharField(default=1, max_length=255, verbose_name='Habilidade da BNCC'),
            preserve_default=False,
        ),
    ]
