# Generated by Django 4.2.2 on 2023-07-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0018_questaoproficiencia_habilidade_bncc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questaoproficiencia',
            old_name='numero_questao_medio',
            new_name='numero_questao_intermediaria',
        ),
        migrations.RenameField(
            model_name='questaoproficiencia',
            old_name='questao_medio',
            new_name='questao_intermediaria',
        ),
    ]
