# Generated by Django 4.2.2 on 2023-07-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0019_rename_numero_questao_medio_questaoproficiencia_numero_questao_intermediaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descritor',
            name='ano',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ano'),
        ),
    ]
