# Generated by Django 4.2.2 on 2023-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0020_descritor_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulado',
            name='tipo_simulado',
            field=models.CharField(blank=True, choices=[('questoes_construidas', 'Simulado Construído'), ('questoes_cadastradas', 'Simulado Cadastrado'), ('questoes_proficiencia', 'Simulado Proficiência'), ('questoes_gerais', 'Simulado Geral')], max_length=255, null=True, verbose_name='Tipo do simulado'),
        ),
    ]
