# Generated by Django 4.2.2 on 2023-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0026_rename_user_responsavel_simulado_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Data limite'),
        ),
        migrations.AddField(
            model_name='simulado',
            name='info_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Informações adicionais'),
        ),
    ]
