# Generated by Django 4.2.2 on 2023-08-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0027_simulado_data_limite_simulado_info_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado'),
        ),
    ]
