# Generated by Django 4.2.2 on 2023-08-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0028_simulado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
