# Generated by Django 4.2.2 on 2023-08-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0029_simulado_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulado',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default='2023-12-12', verbose_name='Data de criação'),
            preserve_default=False,
        ),
    ]
