# Generated by Django 4.2.2 on 2023-08-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0030_alter_simulado_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulado',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='simulado',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-12 10:10:10', verbose_name='Data de criação'),
            preserve_default=False,
        ),
    ]
