# Generated by Django 4.2.2 on 2023-08-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0031_remove_simulado_data_criacao_simulado_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='media_acertos',
            field=models.FloatField(blank=True, null=True, verbose_name='Média de acertos'),
        ),
    ]
