# Generated by Django 4.2.2 on 2023-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0032_simulado_media_acertos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='descritor',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='simulados.descritor', verbose_name='Descritor'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='habilidades_abncc',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='simulados.habilidadesbncc', verbose_name='Habilidades da BNCC'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='habilidades_abncc_texto',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Habilidades da BNCC (Texto)'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='nivel_proficiencia',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='simulados.nivelproficiencia', verbose_name='Nível de proficiência'),
        ),
    ]
