# Generated by Django 4.2.2 on 2023-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0033_alter_questao_descritor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='descritor',
            field=models.ManyToManyField(blank=True, default=None, to='simulados.descritor', verbose_name='Descritor'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='habilidades_abncc',
            field=models.ManyToManyField(blank=True, default=None, to='simulados.habilidadesbncc', verbose_name='Habilidades da BNCC'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='nivel_proficiencia',
            field=models.ManyToManyField(blank=True, default=None, to='simulados.nivelproficiencia', verbose_name='Nível de proficiência'),
        ),
    ]
