# Generated by Django 4.2.2 on 2023-08-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0034_alter_questao_descritor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='nivel_proficiencia',
        ),
        migrations.DeleteModel(
            name='NivelProficiencia',
        ),
    ]
