# Generated by Django 4.2.2 on 2023-08-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0035_remove_questao_nivel_proficiencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=255, verbose_name='Unidade Temática')),
                ('ano', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Unidade Temática',
                'verbose_name_plural': 'Unidades Temáticas',
            },
        ),
        migrations.RemoveField(
            model_name='questao',
            name='descritor',
        ),
        migrations.DeleteModel(
            name='Descritor',
        ),
        migrations.AddField(
            model_name='questao',
            name='unidade_tematica',
            field=models.ManyToManyField(blank=True, default=None, to='simulados.unidadetematica', verbose_name='Unidade Temática'),
        ),
    ]
