# Generated by Django 4.0 on 2024-04-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0036_unidadetematica_remove_questao_descritor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='habilidades_abncc',
            field=models.ManyToManyField(blank=True, default=None, to='simulados.HabilidadesBNCC', verbose_name='Habilidades da BNCC'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='unidade_tematica',
            field=models.ManyToManyField(blank=True, default=None, to='simulados.UnidadeTematica', verbose_name='Unidade Temática'),
        ),
    ]
