# Generated by Django 4.0 on 2024-04-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0037_alter_questao_habilidades_abncc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='matriz_referencial',
            field=models.CharField(choices=[('matematica', 'Matemática'), ('portugues', 'Língua Portuguesa')], default='matematica', max_length=255, verbose_name='Matriz Referencial'),
        ),
    ]
