# Generated by Django 4.0 on 2024-04-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0038_alter_questao_matriz_referencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='habilidades_abncc_texto',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Objeto do Conhecimento'),
        ),
    ]
