# Generated by Django 4.2.9 on 2024-04-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0039_alter_questao_habilidades_abncc_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='componente',
            field=models.CharField(choices=[('Língua Portuguesa', 'Língua Portuguesa'), ('Arte', 'Arte'), ('Educação Física', 'Educação Física'), ('Inglês', 'Inglês'), ('História', 'História'), ('Geografia', 'Geografia'), ('Ensino Religioso', 'Ensino Religioso'), ('Ciências', 'Ciências'), ('Matemática', 'Matemática')], default='Matemática', max_length=255, verbose_name='Componente Curricular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='grau_ensino',
            field=models.CharField(choices=[('1', '1º ano'), ('2', '2º ano'), ('3', '3º ano'), ('4', '4º ano'), ('5', '5º ano'), ('6', '6º ano'), ('7', '7º ano'), ('8', '8º ano'), ('9', '9º ano'), ('10', '1º ano do Ensino Médio'), ('11', '2º ano do Ensino Médio'), ('12', '3º ano do Ensino Médio')], default='1', max_length=255, verbose_name='Grau de Ensino'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='matriz_referencial',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Humanas', 'Humanas'), ('Linguagens', 'Linguagens'), ('Ciências', 'Ciências')], default='Matemática', max_length=255, verbose_name='Matriz Referencial'),
        ),
    ]
