# Generated by Django 4.2.9 on 2024-05-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0042_remove_questao_componente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='descritor',
            field=models.TextField(blank=True, null=True, verbose_name='Descritor'),
        ),
    ]
