# Generated by Django 4.2.9 on 2024-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0043_questao_descritor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulado',
            name='componente',
        ),
        migrations.AddField(
            model_name='questao',
            name='componente',
            field=models.CharField(choices=[('Língua Portuguesa', 'Língua Portuguesa'), ('Arte', 'Arte'), ('Educação Física', 'Educação Física'), ('Inglês', 'Inglês'), ('História', 'História'), ('Geografia', 'Geografia'), ('Ensino Religioso', 'Ensino Religioso'), ('Ciências', 'Ciências'), ('Matemática', 'Matemática')], default='Matemática', max_length=255, verbose_name='Componente Curricular'),
        ),
    ]
