# Generated by Django 4.2.9 on 2024-06-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0046_simulado_rede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidadesbncc',
            name='ano',
            field=models.CharField(blank=True, choices=[('1', '1º ano'), ('2', '2º ano'), ('3', '3º ano'), ('4', '4º ano'), ('5', '5º ano'), ('6', '6º ano'), ('7', '7º ano'), ('8', '8º ano'), ('9', '9º ano'), ('10', '1º ano do Ensino Médio'), ('11', '2º ano do Ensino Médio'), ('12', '3º ano do Ensino Médio')], max_length=255, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='unidadetematica',
            name='ano',
            field=models.CharField(blank=True, choices=[('1', '1º ano'), ('2', '2º ano'), ('3', '3º ano'), ('4', '4º ano'), ('5', '5º ano'), ('6', '6º ano'), ('7', '7º ano'), ('8', '8º ano'), ('9', '9º ano'), ('10', '1º ano do Ensino Médio'), ('11', '2º ano do Ensino Médio'), ('12', '3º ano do Ensino Médio')], max_length=255, null=True, verbose_name='Ano'),
        ),
    ]
