# Generated by Django 4.2.9 on 2024-07-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0047_alter_habilidadesbncc_ano_alter_unidadetematica_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descritor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descritor')),
                ('ano', models.CharField(blank=True, choices=[('1', '1º ano'), ('2', '2º ano'), ('3', '3º ano'), ('4', '4º ano'), ('5', '5º ano'), ('6', '6º ano'), ('7', '7º ano'), ('8', '8º ano'), ('9', '9º ano'), ('10', '1º ano do Ensino Médio'), ('11', '2º ano do Ensino Médio'), ('12', '3º ano do Ensino Médio')], max_length=255, null=True, verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Descritor',
                'verbose_name_plural': 'Descritores',
            },
        ),
    ]
