# Generated by Django 4.2.9 on 2024-07-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0048_descritor'),
    ]

    operations = [
        migrations.AddField(
            model_name='descritor',
            name='unidade_tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulados.unidadetematica', verbose_name='Unidade Temática'),
        ),
        migrations.AddField(
            model_name='habilidadesbncc',
            name='descritor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulados.descritor', verbose_name='Descritor'),
        ),
        migrations.AddField(
            model_name='unidadetematica',
            name='matriz_referencial',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Humanas', 'Humanas'), ('Linguagens', 'Linguagens'), ('Ciências', 'Ciências')], default='Matemática', max_length=255, verbose_name='Matriz Referencial'),
        ),
    ]
