# Generated by Django 4.2.9 on 2024-07-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0049_descritor_unidade_tematica_habilidadesbncc_descritor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=255, verbose_name='Componente Curricular')),
                ('matriz_referencial', models.CharField(choices=[('Matemática', 'Matemática'), ('Humanas', 'Humanas'), ('Linguagens', 'Linguagens'), ('Ciências', 'Ciências')], default='Matemática', max_length=255, verbose_name='Matriz Referencial')),
                ('ano', models.CharField(blank=True, choices=[('1', '1º ano'), ('2', '2º ano'), ('3', '3º ano'), ('4', '4º ano'), ('5', '5º ano'), ('6', '6º ano'), ('7', '7º ano'), ('8', '8º ano'), ('9', '9º ano'), ('10', '1º ano do Ensino Médio'), ('11', '2º ano do Ensino Médio'), ('12', '3º ano do Ensino Médio')], max_length=255, null=True, verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Componente Curricular',
                'verbose_name_plural': 'Componentes Curriculares',
            },
        ),
        migrations.RemoveField(
            model_name='unidadetematica',
            name='matriz_referencial',
        ),
        migrations.AddField(
            model_name='unidadetematica',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulados.componentecurricular', verbose_name='Componente Curricular'),
        ),
    ]
