# Generated by Django 4.2.9 on 2024-07-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0050_componentecurricular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentecurricular',
            name='ano',
        ),
    ]
