# Generated by Django 4.2.9 on 2024-07-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0051_remove_componentecurricular_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descritor',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='habilidadesbncc',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='unidadetematica',
            name='ano',
        ),
    ]
