# Generated by Django 4.2.2 on 2023-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email do Coordenador'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Coordenador'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='nome_escola',
            field=models.CharField(max_length=100, verbose_name='Nome da Escola'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='senha',
            field=models.CharField(max_length=100, verbose_name='Senha do Coordenador'),
        ),
    ]
