# Generated by Django 4.2.2 on 2023-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_coordenador_email_alter_coordenador_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.AddField(
            model_name='coordenador',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço da Escola'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone da Escola'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='turmas',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Turmas da Escola'),
        ),
        migrations.DeleteModel(
            name='Escola',
        ),
    ]
