# Generated by Django 4.2.2 on 2023-06-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_coordenador_options_coordenador_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='escola',
            field=models.CharField(default='escola', max_length=100),
            preserve_default=False,
        ),
    ]
