# Generated by Django 4.2.2 on 2023-07-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_professor_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='nome_escola',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='escola',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.coordenador'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.escola', verbose_name='Escola do Coordenador'),
            preserve_default=False,
        ),
    ]
