# Generated by Django 4.2.2 on 2023-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_escola_estado_escola_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('horario', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='turmas',
        ),
        migrations.AddField(
            model_name='escola',
            name='turma',
            field=models.ManyToManyField(blank=True, to='usuarios.turma'),
        ),
    ]
