# Generated by Django 4.2.2 on 2023-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_turma_remove_coordenador_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='turma',
        ),
        migrations.AddField(
            model_name='escola',
            name='turmas',
            field=models.CharField(blank=True, help_text='Exemplo: 1º ano 01 Vespertino, 2º ano 01 Matutino, 3º ano 01 Vespertino', max_length=300, null=True, verbose_name='Turmas da Escola (separadas por vírgula)'),
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
