# Generated by Django 4.2.2 on 2023-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_escola_turma_escola_turmas_delete_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='turmas',
            field=models.TextField(blank=True, help_text='Exemplo: 1º ano 01 Vespertino, 2º ano 01 Matutino, 3º ano 01 Vespertino', null=True, verbose_name='Turmas da Escola (separadas por vírgula)'),
        ),
    ]
