# Generated by Django 4.2.2 on 2023-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_escola_turmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
