# Generated by Django 4.2.2 on 2023-07-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_professor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
    ]
