# Generated by Django 4.2.2 on 2023-08-02 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0012_secretario'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='cpf',
            field=models.CharField(max_length=11,   verbose_name='CPF (somente números)'),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='username',
            field=models.CharField(max_length=100,  verbose_name='Nome de Usuário'),
        ),
    ]
