# Generated by Django 4.2.2 on 2023-08-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_secretario_user_alter_secretario_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='secretario',
            name='username',
        ),
    ]
