# Generated by Django 4.2.2 on 2023-08-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_escola_secretario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='secretario',
        ),
        migrations.AddField(
            model_name='escola',
            name='Coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.coordenador'),
        ),
    ]
