# Generated by Django 4.2.2 on 2023-08-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_coordenadorgeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadorgeral',
            name='secretario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.secretario'),
        ),
    ]
