# Generated by Django 4.2.2 on 2023-08-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_coordenadorgeral_secretario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenadorgeral',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='coordenadorgeral',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='coordenadorgeral',
            name='municipio',
        ),
    ]
