# Generated by Django 4.2.2 on 2023-08-04 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0020_remove_coordenadorgeral_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='senha',
        ),
        migrations.AddField(
            model_name='coordenador',
            name='coordenador_geral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.coordenadorgeral'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True,   verbose_name='CPF (somente números)'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='nome_completo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordenador',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordenadorgeral',
            name='nome_completo',
            field=models.CharField(max_length=255),
        ),
    ]
