# Generated by Django 4.2.2 on 2023-08-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_remove_coordenador_nome_remove_coordenador_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='cep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escola',
            name='Coordenador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.coordenador'),
        ),
    ]
