# Generated by Django 4.2.2 on 2023-08-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0022_escola_cep_escola_numero_alter_escola_coordenador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='senha',
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default=1, max_length=11,   verbose_name='CPF (somente números)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='nome_completo',
            field=models.CharField(default='nome', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
