# Generated by Django 4.2.2 on 2023-08-11 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_remove_professor_nome_remove_professor_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.escola'),
        ),
    ]
