# Generated by Django 4.2.2 on 2023-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_aluno_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF (somente números)'),
        ),
        migrations.AlterField(
            model_name='coordenadorgeral',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF (somente números)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF (somente números)'),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF (somente números)'),
        ),
    ]
