# Generated by Django 4.2.2 on 2023-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_alter_coordenador_cpf_alter_coordenador_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='coordenadorgeral',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
