# Generated by Django 4.0 on 2024-04-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_alter_coordenador_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='turmas',
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('alunos', models.ManyToManyField(blank=True, to='usuarios.Aluno')),
            ],
        ),
        migrations.AddField(
            model_name='escola',
            name='turmas_escola',
            field=models.ManyToManyField(blank=True, to='usuarios.Turma'),
        ),
    ]
