# Generated by Django 4.0 on 2024-04-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_remove_escola_turmas_escola_turma_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.turma'),
        ),
    ]
