# Generated by Django 4.2.9 on 2024-04-16 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_remove_aluno_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='Coordenador',
        ),
        migrations.AddField(
            model_name='coordenador',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.escola'),
        ),
    ]
