# Generated by Django 4.2.9 on 2024-04-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_remove_escola_cep_remove_escola_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='grau',
            field=models.CharField(choices=[('1', '1º ano'), ('2', '2º ano'), ('3', '3º ano'), ('4', '4º ano'), ('5', '5º ano'), ('6', '6º ano'), ('7', '7º ano'), ('8', '8º ano'), ('9', '9º ano'), ('10', '1º ano do ensino médio'), ('11', '2º ano do ensino médio'), ('12', '3º ano do ensino médio')], default='1', max_length=100),
        ),
    ]
