# Generated by Django 4.2.9 on 2024-05-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0044_remove_simulado_componente_questao_componente'),
        ('usuarios', '0034_turma_grau'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='simulados_respondidos',
            field=models.ManyToManyField(blank=True, to='simulados.simulado'),
        ),
    ]
