# Generated by Django 4.2.9 on 2024-05-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_turma_simulados_respondidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': 'Coordenador de Escola', 'verbose_name_plural': 'Coordenadores de Escola'},
        ),
    ]
