# Generated by Django 4.2.9 on 2024-06-15 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_secretario_rede'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='rede',
            field=models.CharField(default='Estadual', max_length=100),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='escola',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.escola'),
        ),
    ]
